# Generated by Django 3.2.4 on 2023-08-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='token',
            new_name='forget_password_token',
        ),
    ]
